# Generated by Django 5.0.6 on 2024-07-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_student_contact_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_No',
            field=models.CharField(max_length=10),
        ),
    ]
