# Generated by Django 5.0.6 on 2024-07-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_student_contact_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_No',
        ),
    ]
