# Generated by Django 5.0.6 on 2024-07-04 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_remove_student_contact_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benches', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='class_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='info.classroom'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('class_rooms', models.ManyToManyField(to='info.classroom')),
            ],
        ),
    ]
