# Generated by Django 5.0.6 on 2024-07-04 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0005_classroom_student_class_room_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
